spring.application.name=springboot-postbook
spring.datasource.url=jdbc:postgresql://localhost:5432/postbook
spring.datasource.username=postgres
spring.datasource.password=tetsuyavirtus

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080